### ISSUE TITLE
Add support for downloading in the background

### ISSUE THREAD

**Issue by hajajmaor** [nabil6391/flutter_download_manager#1]
Suggestion:
Each download should have a different isolate, but if adding a background process and spawning the isolates, I think it should work.

**Comment by micodev** [comment]
keep up  , looking for that feature ( very important one )
😍😍😍

**Comment by nabil6391** [comment]
Thanks for the suggestion guys, the downloading of the files are already async and does not block the UI thread. So what do you think would the benefits be for using an isolate here.
