### ISSUE TITLE
None of the listeners are being called 

### ISSUE THREAD

**Issue by nergal79** [nabil6391/flutter_download_manager#18]
I am trying to download a file and I think I followed the doc right .. but status and progress update listeners never gets called.. below is the method i m using .. is there anything wrong with my implementation ? 

> addDownloadToQueue(String? url) async {
    if (url == null) return;
    final downloadDir = _getSaveDirectory();
    _downloadManager.addDownload(url, downloadDir);
    DownloadTask? task = _downloadManager.getDownload(url);
    task?.status.addListener(() {
      logger.e(task.status.value);
    });
    task?.progress.addListener(() {
      logger.e(task.progress.value);
    });
    await _downloadManager.whenDownloadComplete(url);
  }

**Comment by zenosama1111** [comment]
getDownload is not working for me either but I managed to make this thing work. instead of using that code, try this.

```
addDownloadToQueue(List<String> urls) async {
for(var url in urls) {
final downloadDir = '${_getSaveDirectory()}/${_downloadManager.getFileNameFromUrl(url)}'; 
DownloadTask? task = await _downloadManager.addDownload(url, downloadDir);
task!.status.addListener(() {
logger.e(task.status.value);
});
task!.progress.addListener(() {
logger.e(task.progress.value);
});
}

var batchProgress = dm.getBatchDownloadProgress(urls);
batchProgress.addListener(() {
print(batchProgress.value);
}
await dm.whenBatchDownloadsComplete(urls);
}
```
