### ISSUE TITLE
Add Platform.pathSeparator instead putting "/" when building the directory.

### ISSUE THREAD

**Issue by ortolanph** [nabil6391/flutter_download_manager#5]
At the `downloader.dart` file, on the `addDownload` method there is a `/` hardcoded. Suggestion to replace by `Platform.pathSeparator`, because of Windows systems (yeah... you know, multiplatform stuff).

```
      var downloadFilename = isDirectory
          ? savedDir + Platform.pathSeparator + getFileNameFromUrl(url)
          : savedDir;
```

**Comment by nabil6391** [comment]
Good Suggestion!, I will try to fix that up. I dont mind a PR as well.

**Comment by ortolanph** [comment]
I can do it... Soon there will be a PR for you.

**Comment by ortolanph** [comment]
Fix done and created a PR. Thanks for allowing me to help with something! Please check my PR.
