### ISSUE TITLE
How can we use it with sqflite and provider?

### ISSUE THREAD

**Issue by burhanaksendir** [nabil6391/flutter_download_manager#6]
Hello,
Thank you for this good project. Can you share an example of how to use Download Manager with Sqflite and Provider?

**Comment by nabil6391** [comment]
Hi, whats your usecase? How do you want to connect with them?

**Comment by burhanaksendir** [comment]
Thank you very much for your reply. I'm new to Flutter. There are 2 simple tables in the database. sounds (id, title, url)
downloads (id, soundID, progress, status)

I want to pull the urls in Download Manager from the database and save the download statuses in the database.
When the application is opened again, I want to see all the download values (progress, states etc) from the downloads table in the database.

**Comment by nabil6391** [comment]
You should able to hook them up just normally
